
-- Liste des trajets entre deux zones données à une date donnée : ici le 01/01/2021, entre les zones 1 et 2.
-- Pourrait être généralisée grâce à une fonction.

select TD.NUMERO_TRAJET, TD.DATE_DEPART, TD.HEURE_DEPART, TD.NUMERO_CREATEUR, TD.NUMERO_EVENEMENT,
	TD.LIEU_DEPART, LD.NOM_LIEU as NOM_LIEU_DEPART, LD.ADRESSE_LIEU as ADRESSE_DEPART, LD.NUMERO_ZONE as ZONE_DEPART,
	TA.LIEU_ARRIVEE, LA.NOM_LIEU as NOM_LIEU_ARRIVEE, LA.ADRESSE_LIEU as ADRESSE_ARRIVEE, LA.NUMERO_ZONE as ZONE_ARRIVEE
	from (TRAJET as TD inner join LIEU as LD on TD.LIEU_DEPART=LD.NUMERO_LIEU) inner join
	(TRAJET as TA inner join LIEU as LA on TA.LIEU_ARRIVEE=LA.NUMERO_LIEU) using(DATE_DEPART,HEURE_DEPART)
	where DATE_DEPART = "2021-01-01" and (LD.NUMERO_ZONE=1 or LD.NUMERO_ZONE=2 or LA.NUMERO_ZONE=1 or LA.NUMERO_ZONE=2);

-- Liste des trajets sans événement.

select * from TRAJET where NUMERO_EVENEMENT is null;

-- Liste des paires d'étudiants ayant voyagé ensemble au moins une fois.

select distinct E1.NUMERO_ETUDIANT as NO_ETUDIANT_1, E1.NOM_ETUDIANT as NOM_ETUDIANT_1, E1.PRENOM_ETUDIANT as PRENOM_ETUDIANT_1,
	E2.PRENOM_ETUDIANT as PRENOM_ETUDIANT_2, E2.NOM_ETUDIANT as NOM_ETUDIANT_2, E2.NUMERO_ETUDIANT as NO_ETUDIANT_2
	from (ETUDIANT as E1,ETUDIANT as E2) inner join (INSCRIPTION as I1, INSCRIPTION as I2)
	on (E1.NUMERO_ETUDIANT=I1.NUMERO_ETUDIANT and E2.NUMERO_ETUDIANT=I2.NUMERO_ETUDIANT
	and E1.NUMERO_ETUDIANT<E2.NUMERO_ETUDIANT)
	where (I1.NUMERO_TRAJET=I2.NUMERO_TRAJET)
	group by E1.NUMERO_ETUDIANT,E2.NUMERO_ETUDIANT;
